const STATE_CAMPS = {
  abia: { id: '', state_name: 'ABIA', address: "NYSC Permanent Orientation Camp, Umunna, Bende Local Government Area, Abia State." },
  adamawa: { id: '', state_name: 'ADAMAWA', address: "NYSC Permanent Orientation Camp, Lapondo Road, Damare, Girei LGA, Adamawa State." },
  akwa_ibom: { id: '', state_name: 'AKWA IBOM', address: "NYSC Permanent Orientation Camp, Ikot Itie Udung, Nsit Atai Local Government Area, Akwa Ibom State." },
  anambra: { id: '', state_name: 'ANAMBRA', address: "NYSC Permanent Orientation Camp, Progressive Senior Secondary School, Umunya, Oyi Local Government Area, Anambra State." },
  bauchi: { id: '', state_name: 'BAUCHI', address: "NYSC Permanent Orientation camp, KM 60 Wailo, Ganjuwa Local Government Council, bauchi State" },
  bayelsa: { id: '', state_name: 'BAYELSA', address: "Kaiama Grammar School , Kaiama, Kolokuma/Opokuma L.G.A Kaiama Grammar School, Kaiama, Kolokoma-Opokuma Local Government Area, Bayelsa State." },
  benue: { id: '', state_name: 'BENUE', address: "NYSC Permanent Orientation Camp, Wannune, Tarka Local Government Area, Kilometer 35 Makurdi Gboko Road, Benue State." },
  borno: { id: '', state_name: 'BORNO', address: "College of Peace and Disaster Management, Nigeria Security and Civil Defence Corps (NSCDC), Babbar-Ruga Batsari Road Katsina, Katsina State." },
  cross_river: { id: '', state_name: 'CROSS RIVER', address: "NYSC Permanent Orientation Camp, Obubra, Obubra Local Government Area, Cross River State." },
  delta: { id: '', state_name: 'DELTA', address: "NYSC Permanent Orientation Camp Former Martins TTC, Issele-Uku, Aniocha North L.G.A. Delta State." },
  ebonyi: { id: '', state_name: 'EBONYI', address: "NYSC Permanent Orientation Camp, Macgregor College, Afikpo Local Government Area, Ebonyi State." },
  edo: { id: '', state_name: 'EDO', address: "Okada Grammar School, Okada, Ovia North-East Local Government Area, Edo State." },
  ekiti: { id: '', state_name: 'EKITI', address: "NYSC Permanent Orientation Camp, Ise-Orun/Emure Local Government Area, Ekiti State." },
  enugu: { id: '', state_name: 'ENUGU', address: "NYSC Permanent Orientation Camp, Awgu Local Government Area, Enugu State." },
  fct: { id: '', state_name: 'FCT (ABUJA)', address: "NYSC Permanent Orientation Camp, Kubwa, Bwari Area Council, FCT." },
  gombe: { id: '', state_name: 'GOMBE', address: "NYSC Temporary Orientation Camp, Science Technical College, Amada, KM 21, Gombe-Bauchi Highway, Near International Airport, Gombe State." },
  imo: { id: '', state_name: 'IMO', address: "NYSC Temporary Orientation Camp Former Girl's Model Secondary School Eziama Obaire Nkwerre Local Govt Area, Imo State." },
  jigawa: { id: '', state_name: 'JIGAWA', address: "NYSC Permanent Camp, opposite Army Barrack, Fanisua Dutse Local Government Area, Jigawa State." },
  kaduna: { id: '', state_name: 'KADUNA', address: "NYSC Permanent Orientation Camp, Kaduna – Abuja Road, Kaduna State." },
  kano: { id: '', state_name: 'KANO', address: "NYSC Permanent Orientation Camp, Kusala Dam, Karaye, Karaye Local Government, Kano State." },
  katsina: { id: '', state_name: 'KATSINA', address: "Youth Multi-purpose Centre/ NYSC Permanent Orientation Camp, Mani Road, Katsina State." },
  kebbi: { id: '', state_name: 'KEBBI', address: "NYSC Permanent Orientation Camp, Dakingari Local Government Area, Kebbi State." },
  kogi: { id: '', state_name: 'KOGI', address: "NYSC Permanent Orientation Camp, Asaya, Kabba Local Government Area, Kogi State." },
  kwara: { id: '', state_name: 'KWARA', address: "NYSC Permanent Orientation Camp, Yikpata, Edu Local Government Area, Kwara State." },
  lagos: { id: '', state_name: 'LAGOS', address: "NYSC Permanent Orientation Camp, Iyana Ipaja, Agege, Lagos State." },
  nassarawa: { id: '', state_name: 'NASSARAWA', address: "Magaji Dan-Yamusa Permanent Orientation Camp, Keffi, Nasarawa State." },
  niger: { id: '', state_name: 'NIGER', address: "NYSC Permanent Orientation Camp, (Former Abubakar, Dada Senior Secondary School), Paiko, Niger State." },
  ogun: { id: '', state_name: 'OGUN', address: "NYSC Permanent Orientation Camp, Ikenne Road, Sagamu Local Government Area, Sagamu, Ogun State." },
  ondo: { id: '', state_name: 'ONDO', address: "NYSC Permanent Orientation Camp, Ikare-Akoko Local Government Area, Ondo State." },
  osun: { id: '', state_name: 'OSUN', address: "NYSC Permanent Orientation Camp, Aisu College Hospital Road, Ede North Local Government Area, Ede, Osun State." },
  oyo: { id: '', state_name: 'OYO', address: "Government Technical College, Iseyin Local Government Area, Iseyin, Oyo State." },
  plateau: { id: '', state_name: 'PLATEAU', address: "NYSC Permanent Orientation Camp, Mangu, Mangu Local Government Area, Plateau State." },
  rivers: { id: '', state_name: 'RIVERS', address: "NYSC Permanent Orientation Camp, Nonwa-Gbam Tai Local Government Area, Rivers State." },
  sokoto: { id: '', state_name: 'SOKOTO', address: "NYSC Permanent Orientation Camp, Wamakko,Wamakko Local Govt Area, Sokoto State." },
  taraba: { id: '', state_name: 'TARABA', address: "NYSC Permanent Orientation Camp, Sibre Airport Road, Jalingo, Taraba State." },
  yobe: { id: '', state_name: 'YOBE', address: "College of Administration and Business Studies, Potiskum, Yobe State." },
  zamfara: { id: '', state_name: 'ZAMFARA', address: "NYSC Permanent Orientation Camp, Beside FRSC Office, Tsafe Local Government Area, Zamfara State." },
}

export default STATE_CAMPS;